#include BOARD_HEADER

#ifndef INCLUDE_MOTOR_MOTOR_HACKER_A40_14L_H_
#define INCLUDE_MOTOR_MOTOR_HACKER_A40_14L_H_

#define USER_MOTOR_NAME "A40_14L"
#define USER_MOTOR MOTOR_HACKER_A40_14L
#define nUSER_MOTOR_TYPE MOTOR_Type_Pm
#define nUSER_MOTOR_NUM_POLE_PAIRS (7)
#define nUSER_MOTOR_Rr (NULL)
#define nUSER_MOTOR_Rs (0.033603661)
#define nUSER_MOTOR_Ls_d (1.989e-05)
#define nUSER_MOTOR_Ls_q (1.989e-05)
#define nUSER_MOTOR_RATED_FLUX (0.016237421)
#define nUSER_MOTOR_MAGNETIZING_CURRENT (NULL)
#define nUSER_MOTOR_RES_EST_CURRENT (2)
#define nUSER_MOTOR_IND_EST_CURRENT (-1)
#define nUSER_MOTOR_MAX_CURRENT (70.0)  //(40.0)
#define nUSER_MOTOR_FLUX_EST_FREQ_Hz (60.0)

#define nUSER_MOTOR_KP _IQ(0.5)
#define nUSER_MOTOR_KI _IQ(0.005)

#define nUSER_MAX_SPEED (4.5)

#endif /* INCLUDE_MOTOR_MOTOR_HACKER_A40_14L_H_ */
