#ifndef INCLUDE_MOTOR_MOTOR_BELT_DRIVE_WASHER_IPM_H_
#define INCLUDE_MOTOR_MOTOR_BELT_DRIVE_WASHER_IPM_H_

#define USER_MOTOR_NAME "Washer_IPM"
#define USER_MOTOR_TYPE MOTOR_Type_Pm
#define USER_MOTOR_NUM_POLE_PAIRS (4)
#define USER_MOTOR_Rr (NULL)
#define USER_MOTOR_Rs (2.832002)
#define USER_MOTOR_Ls_d (0.0115)
#define USER_MOTOR_Ls_q (0.0135)
#define USER_MOTOR_RATED_FLUX (0.5022156)
#define USER_MOTOR_MAGNETIZING_CURRENT (NULL)
#define USER_MOTOR_RES_EST_CURRENT (1.0)
#define USER_MOTOR_IND_EST_CURRENT (-1.0)
#define USER_MOTOR_MAX_CURRENT (4.0)
#define USER_MOTOR_FLUX_EST_FREQ_Hz (20.0)

#define USER_MOTOR_KP _IQ(0.0)
#define USER_MOTOR_KI _IQ(0.0)

#define USER_MAX_SPEED (3.5)

#endif /* INCLUDE_MOTOR_MOTOR_BELT_DRIVE_WASHER_IPM_H_ */
