#ifndef INCLUDE_MOTOR_MOTOR_EFLITE_POWER10_H_
#define INCLUDE_MOTOR_MOTOR_EFLITE_POWER10_H_

#define USER_MOTOR_NAME "Eflite10"
#define USER_MOTOR MOTOR_Eflite_power10
#define USER_MOTOR_TYPE MOTOR_Type_Pm
#define USER_MOTOR_NUM_POLE_PAIRS (7)
#define USER_MOTOR_Rr (NULL)
#define USER_MOTOR_Rs (0.0210812781)
#define USER_MOTOR_Ls_d (1.82850908e-06)
#define USER_MOTOR_Ls_q (1.82850908e-06)
#define USER_MOTOR_RATED_FLUX (0.00459952652)
#define USER_MOTOR_MAGNETIZING_CURRENT (NULL)
#define USER_MOTOR_RES_EST_CURRENT (2)
#define USER_MOTOR_IND_EST_CURRENT (-1)
#define USER_MOTOR_MAX_CURRENT (15.0)
#define USER_MOTOR_FLUX_EST_FREQ_Hz (50.0)

#define USER_MOTOR_KP _IQ(0.0)
#define USER_MOTOR_KI _IQ(0.0)

#define USER_MAX_SPEED (15.0)

#endif /* INCLUDE_MOTOR_MOTOR_EFLITE_POWER10_H_ */
