#ifndef INCLUDE_USER_USER_CONFIG_H_
#define INCLUDE_USER_USER_CONFIG_H_

#define USER_NODE_ID (6)
#define USER_DEVICE_ASSIGNMENT USER_NODE_ID
#define USER_STATUS_BROADCAST_PERIOD_US (25U)

#define ECAN_BUF_SIZE 16

// #define APP_NODE_NAME "org.ipm.WM18"

#endif /* INCLUDE_USER_USER_CONFIG_H_ */
